name: ci
on:
  push:
    branches: [ main, dev ]
    tags:
      - v*
  pull_request:
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
